Testsuggestion
wolox-training/ge-rails pull request #19
Opened 2017-09-14 18:58 UTC by gonziesc

## Summary
- Adding tests for creating suggestions endpoint

## Trello Card
https://trello.com/c/ljKCQ9tL/31-crear-test-para-endpoint-de-creaci%C3%B3n-de-un-booksuggestion

2017-09-15 15:04 UTC, hdf1996 requested changes

2017-09-15 15:04 UTC, hdf1986 commented on spec/controllers/api/v1/book_suggestions_controller_spec.rb
> +        end.to change { BookSuggestion.count }.by(0)
You can use `to_not change` here

2017-09-15 15:05 UTC, hdf1986 commented on spec/controllers/api/v1/book_suggestions_controller_spec.rb
> +# rubocop:disable Metrics/BlockLength
You can disable this on rubocop.yml just in the specs

2017-09-18 16:50 UTC, hdf1996 approved these changes

2017-09-18 16:54 UTC, merged